### ISSUE TITLE
ERR When using redis UClansSync as addon

### ISSUE THREAD

**Issue by Gx678X** [saicone/UClanSync#1]
[19:52:09 WARN]: [UltimateClans] Plugin UltimateClans v4.9.1 generated an exception while executing task 487
com.saicone.uclansync.lib.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'auth' command
        at com.saicone.uclansync.lib.jedis.Protocol.processError(Protocol.java:96) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Protocol.process(Protocol.java:137) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Protocol.read(Protocol.java:192) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Connection.getStatusCodeReply(Connection.java:243) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Connection.auth(Connection.java:377) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Connection.initializeFromClientConfig(Connection.java:343) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Connection.<init>(Connection.java:53) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Jedis.<init>(Jedis.java:214) ~[?:?]
        at com.saicone.uclansync.lib.jedis.JedisFactory.makeObject(JedisFactory.java:181) ~[?:?]
        at com.saicone.uclansync.lib.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[?:?]
        at com.saicone.uclansync.lib.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[?:?]
        at com.saicone.uclansync.lib.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[?:?]
        at com.saicone.uclansync.lib.jedis.util.Pool.getResource(Pool.java:34) ~[?:?]
        at com.saicone.uclansync.lib.jedis.JedisPool.getResource(JedisPool.java:364) ~[?:?]
        at com.saicone.uclansync.core.messenger.type.RedisMessenger.sendMessage(RedisMessenger.java:103) ~[?:?]
        at com.saicone.uclansync.core.messenger.Messenger.send(Messenger.java:87) ~[?:?]
        at com.saicone.uclansync.core.ClanUpdater.lambda$sendMessage$2(ClanUpdater.java:112) ~[?:?]

**Comment by Rubenicos** [comment]
What is your redis version?
This is an error related with redis server.

So, try to change the redis connection URL `redis://:` -> `redis://`

**Comment by Gx678X** [comment]
My url already looks like this
    url: 'redis://root:pass@127.0.0.1:6379/0'

Redis version is : 5.0.7
is anyway to make the redis settings look like this instead of URL? :

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""

**Comment by Rubenicos** [comment]
Try to set as `redis://pass@127.0.0.1:6379/0` or `redis://h:pass@127.0.0.1:6379/0`.

**Comment by Gx678X** [comment]
With the first URL I get this
[19:10:39] [Server thread/INFO]: [UClanSync] Enabling UClanSync addon...
[19:10:39] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.util.JedisURIHelper.getPassword(JedisURIHelper.java:36)
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.JedisFactory.<init>(JedisFactory.java:131)
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.JedisFactory.<init>(JedisFactory.java:119)
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.JedisPool.<init>(JedisPool.java:346)
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.JedisPool.<init>(JedisPool.java:340)
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.JedisPool.<init>(JedisPool.java:329)
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.JedisPool.<init>(JedisPool.java:318)
[19:10:39] [Server thread/WARN]: 	at com.saicone.uclansync.lib.jedis.JedisPool.<init>(JedisPool.java:66)
With the second one:
[19:15:30 WARN]: [UltimateClans] Plugin UltimateClans v4.9.1 generated an exception while executing task 233
com.saicone.uclansync.lib.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'auth' command
        at com.saicone.uclansync.lib.jedis.Protocol.processError(Protocol.java:96) ~[?:?]
        at com.saicone.uclansync.lib.jedis.Protocol.process(Protocol.java:137) ~[?:?]

**Comment by Rubenicos** [comment]
Update your Redis server version to 6.0 or higher, and use the url like this `redis://:pass@127.0.0.1:6379/0`, this problem is related to your Redis server and seems that UClanSync is only compatible with newer versions of Redis.

**Comment by Gx678X** [comment]
Yes looks like the issue was the version, i updated to the lastest v6 and now no err popping.

So one question I had is, this plugin substitutes multiserver addon uclan ? (I mean if i dont need that addon, with this one)

**Comment by Rubenicos** [comment]
Yeah, it's a substitute
